### ISSUE TITLE
issue: process is not defined

### ISSUE THREAD

**Issue by floifydaniel** [mammadataei/cypress-vite#2]
Thanks for making this package! I've followed the installation steps but getting a `process is not defined` error in my e2e test. Not sure what's going on but hoping maybe you know something I don't. Any ideas? I looked at your most recent commit to upgrade to Vite 3 but still stumped.

# Environment

- `cypress@^10.3.1`
- `vite@^3.0.0`
- `cypress-vite@^1.0.2`

# Files

Main `tsconfig.json` at the root of my project

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "target": "ESNext",
    "useDefineForClassFields": true,
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "allowJs": false,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "types": ["cypress"]
  },
  "exclude": ["**/node_modules", "**/dist"]
}
```

Which is extended in my main project's directory

```json
{
  "extends": "../../tsconfig.json",
  "include": ["src/**/*", "cypress/**/*"],
  "references": [{ "path": "./tsconfig.node.json" }]
}
```

That also has `tsconfig.node.json`

```json
{
  "compilerOptions": {
    "composite": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "allowSyntheticDefaultImports": true
  },
  "include": ["vite.config.ts"]
}
```

And `vite.config.ts`

```js
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

export default defineConfig({
  plugins: [react()],
});
```

My `cypress.config.ts` looks like this

```js
import { defineConfig } from "cypress";
import vitePreprocessor from "cypress-vite";

export default defineConfig({
  e2e: {
    baseUrl: "http://localhost:5173",
    setupNodeEvents(on, config) {
      on("file:preprocessor", vitePreprocessor());
    },
  },
});
```

**Comment by mammadataei** [comment]
This is because of vite 3 changes as described here https://github.com/vitejs/vite/pull/8090. I think it must be fixed in #1, just didn't release it yet.

**Comment by mammadataei** [comment]
[v.1.1.0](https://github.com/mammadataei/cypress-vite/releases/tag/v1.1.0) release. I hope it solves this.

**Comment by floifydaniel** [comment]
@mammadataei it seems to have fixed this. One thing that might helpful to add to the docs is it requires `NODE_ENV` to be set before it'll work otherwise it emits the error `Invalid NODE_ENV`. For example, my `open` command looks like this: `NODE_ENV=development yarn cypress open`. Thanks for your time addressing this, I'll close out the issue.
