### ISSUE TITLE
[Vite] WS Proxy Error in Vue 3 Application while running Cypress in Github Actions CI/CD

### ISSUE THREAD

**Issue by rizypb** [mammadataei/cypress-vite#34]
I am using Cypress 12.5.0 version in a `Vue.js 3` app along with `vite` (4.0.4) and `cypress-vite` (1.3.0) but during the CI/CD in Github actions, its throwing this error while running the E2E tests: 
```
7:25:07 AM [vite] ws proxy error:
Error: socket hang up
    at connResetException (internal/errors.js:639:14)
    at TLSSocket.socketCloseListener (_http_client.js:449:25)
    at TLSSocket.emit (events.js:412:35)
    at net.js:686:12
    at TCP.done (_tls_wrap.js:564:7)
```
I am using proxy in port 8080 with the backend APIs while running the app locally. Any idea what's I am missing here? This is my proxy configuration in `vite.config.ts` file:
```
  server: {
      port: 8080,
      proxy: {
        '^/api/': {
          target: process.env.VITE_APP_PROXY_API,
          changeOrigin: true,
          secure: false,
          rewrite: (path) => path.replace('/api/', '')
        }
      }
    }
```

And here's the `cypress.config.ts` file:
  ```
e2e: {
    specPattern: 'tests/e2e/specs/**/*.{js,jsx,ts,tsx}',
    supportFile: 'tests/e2e/support/index.js',
    experimentalRunAllSpecs: true,
    baseUrl: 'http://localhost:8080',
    setupNodeEvents(on, config) {
      return cypressPlugin(on, config);
    }
  }
```
Any idea what's I am missing here?

**Comment by mammadataei** [comment]
I'm not sure if this is related to `cypress-vite`, but I'll be glad to help with debugging if you can create a minimal reproduction.
You can also check the [debug output](https://github.com/mammadataei/cypress-vite#debugging) to see if cypress-vite throws any errors.
