### ISSUE TITLE
Configfile Error on cypress.config.ts

### ISSUE THREAD

**Issue by sgnilreutr** [mammadataei/cypress-vite#4]
```
import path from 'path'
import { defineConfig } from 'cypress'
import vitePreprocessor from 'cypress-vite'

 e2e: {
    setupNodeEvents(on, config) {
      on(
        'file:preprocessor',
        vitePreprocessor(path.resolve(__dirname, './vite.config.ts'))
      )
    },

```

A partial snippet of the config.

Running on.
"cypress": "^10.6.0",
"cypress-vite": "^1.1.1",

Gives:
![Screenshot 2022-08-17 at 08 43 04](https://user-images.githubusercontent.com/41041655/185052613-785d8190-8351-4011-bc21-0b3575b5ea11.png)

----
When removing the path setup, to just be the file, it doesn't error.
I've also tried path-browserify, given that there might be a chance that vite has externalized it.

What did I do wrong? Since I was following your instructions.

**Comment by mammadataei** [comment]
Can you try this:

```typescript
import { resolve } from 'path'

vitePreprocessor(resolve(__dirname, './vite.config.ts'))
```

**Comment by sgnilreutr** [comment]
Hey

That fixed the issue :), thanks!
