### ISSUE TITLE
Cypress looking for .ts files but build output are .js files

### ISSUE THREAD

**Issue by lauhon** [mammadataei/cypress-vite#41]
Hi there,

I was curious to try out this package in an angular project with cypress e2e tests written in typescript.

My e2e tests existed before and were working. When I install and setup `cypress-vite` in the most minimal way

```cypress.config.ts
...
e2e: {
setupNodeEvents(on, config) {
      on(
        'file:preprocessor',
        vitePreprocessor(),
      )
}
```

I get following error in the cypress UI:

```
Error: ENOENT: no such file or directory, 
stat '/path-to-cypress-build/bundles/cypress/e2e/dashboard/dashboard.cy.ts'
```

when I check out that folder I can see that a `dashboard.cy.ts.js` file exists.

I guess I just have to configure cypress to look for .js files instead of .ts files?
Or can I configure vite to preserve the .ts files?

The second option seems weird to me because isn't it one purpose to use vite for transpilation?

**Comment by sampullman** [comment]
I think this is a duplicate of #33, or at least related. We experienced the same issue in our monorepo, and solved it by adding a `vite.config.ts` (which didn't exist in the e2e project yet), and referencing it in `cypress.config.ts` as indicated [here](https://github.com/mammadataei/cypress-vite/issues/33#issuecomment-1401306497)

**Comment by lauhon** [comment]
Thanks for your answer!

In the Issue you linked I can see that you configured `vitePreprocessor` to look for a vite config, but I am missing what the content of the vite config actually was. Do you know what config actually fixed the Issue?

(I already tried to pass an empty vite config in my setup, but the problem remained)

**Comment by sampullman** [comment]
Well this is odd, a blank config (`export default defineConfig({})`) works in our case. Not only that, but I tried removing the config/viteProcessor initialization and it still works. I suspect it's a caching issue, maybe you can try deleting `~/Library/Application\ Support/Cypress/cy/production/projects/<your-project-name>/`? The only other things I've done since the bug occurred are deleting node_modules/package-lock.json, and install/removing some other packages.

**Comment by mammadataei** [comment]
Hi @lauhon, can you try to run cypress in debug mode:
`DEBUG=cypress-vite cypress open`
It will reveal if there is a compilation error.

**Comment by lauhon** [comment]
Hey, 

so putting both of your answers together I could find the problem, it was a missing config on my side.
In the project, we have ts-config alias paths which of course were missing in my empty vite config.

I fixed the issue by installing 

[vite-tsconfig-paths](https://www.npmjs.com/package/vite-tsconfig-paths)

And defining my vite config like 

```export default defineConfig({ plugins: [tsconfigPaths()] })```
