### ISSUE TITLE
ReferenceError: __dirname is not defined

### ISSUE THREAD

**Issue by Acetyld** [mammadataei/cypress-vite#64]
I keep getting the following:

Any clue why?

<img width="907" alt="Screenshot 2023-07-07 at 18 45 23" src="https://github.com/mammadataei/cypress-vite/assets/55088242/0013ad00-7385-4df4-8d38-f4162bcf245d">

![Screenshot 2023-07-07 at 18 46 42](https://github.com/mammadataei/cypress-vite/assets/55088242/1ecb6600-40c2-4eb5-857f-ffd22e09e056)

**Comment by mammadataei** [comment]
I think you have `"type": "module"` in your `package.json`. [This article](https://byby.dev/node-dirname-not-defined#:~:text=The%20error%20message%20%E2%80%9C__dirname,dirname%20variable%20available%20by%20default.) might help.
