### ISSUE TITLE
Is dev server supposed to run on its own?

### ISSUE THREAD

**Issue by dirago** [mammadataei/cypress-vite#8]
Hey there,

I'm struggling to run the tests, even with the example provided in the repo, I surely miss something but can't see what it is.

context: cypress-vite repo

```sh
cd example && npm i && npm run test
```

But Cypress keeps saying server is not running:

```sh
Cypress could not verify that this server is running:

  > http://localhost:5173/

We are verifying this server because it has been configured as your baseUrl.

Cypress automatically waits until your server is accessible before running tests.
```

What do I do wrong? Thanks

**Comment by mammadataei** [comment]
Hi, no, `cypress-vite` has nothing to do with your app's dev server; it only compiles e2e spec files using vite. You need to start the dev server manually. You can also use [start-server-and-test](https://github.com/bahmutov/start-server-and-test) or [concurrently](https://www.npmjs.com/package/concurrently) to start the server and run tests within a single command.

The reason I didn't use either in the `example` package is that in CI, `cypress-io/github-action@v4` starts the dev server itself. (Maybe I should separate the CI command!)

https://github.com/mammadataei/cypress-vite/blob/0738fbe8188d2d679982dc2339cc1fbff0c883c7/.github/workflows/check.yaml#L87

**Comment by mammadataei** [comment]
I've added concurrently to the example. You can check it [here](https://github.com/mammadataei/cypress-vite/commit/b00776c4644f4df394dcc6c8b55a51d4476800e3).

**Comment by dirago** [comment]
oh ok, I thought it would start the server automatically, my bad, thanks @mammadataei for your answer!
