### ISSUE TITLE
plugins from supportFile not loaded

### ISSUE THREAD

**Issue by batje** [mammadataei/cypress-vite#9]
My cypress.config.ts file contains the line
```
    supportFile: 'tests/cypress/support/e2e.ts',
```
But the import statements in that file

```
import '@cypress/code-coverage/support';
import 'cypress-plugin-tab';
import 'cypress-file-upload';
```

All of them do not seem to be loading. Am I doing something wrong?

**Comment by mammadataei** [comment]
@batje thanks for reporting. Can you help me with more context about the problem? like cypress and typescript configurations, or maybe a reproduction if possible.

**Comment by batje** [comment]
I tried setup a project from scratch, and of course that project works exactly as it should. I cant introduce the bug there, so it's probably mine. sorry to have bothered you.
